### ISSUE TITLE
ssl and websocket error

### ISSUE THREAD

**Issue by mndphaser** [martinju/stromstotte#2]
Hi,
https://i.imgur.com/IAnUBWa.png I'm getting this and if you have forward to HTTPS-Only Mode the page is not working. Add HTTPS support on the server side?

**Comment by martinju** [comment]
Hi. Thanks for reporting. Will fix this within a couple of days.

**Comment by martinju** [comment]
Https should be up and running now. Please let me know if you got further issues.
