### ISSUE TITLE
Endret pris på energiledd hos Agder Energi

### ISSUE THREAD

**Issue by jfooobet** [martinju/stromstotte#6]
Endres videre fra 1. okt 23

https://www.aenett.no/nettleie/tariffer/

**Comment by martinju** [comment]
Takk for info. Det er oppdatert manuelt nå i commit https://github.com/martinju/stromstotte/commit/17fcd34891f32a2ef285fcb13630d935101ae2c5
Jobber med automatisk oppdatering for fremtiden.
