### ISSUE TITLE
Ikke oppdatert nettleie for L-Nett pr

### ISSUE THREAD

**Issue by Blodstrupmo1** [martinju/stromstotte#8]
![image](https://github.com/martinju/stromstotte/assets/74018928/5f7097b1-1e09-4ae2-99c5-858ed84a102d)

**Comment by martinju** [comment]
Takk for info. Det er oppdatert manuelt nå i commit https://github.com/martinju/stromstotte/commit/17fcd34891f32a2ef285fcb13630d935101ae2c5
Jobber med automatisk oppdatering for fremtiden.
