### ISSUE TITLE
Prisjustert terskelverdi

### ISSUE THREAD

**Issue by kardesken** [martinju/stromstotte#9]
Det virker som om at denne siden fortsatt bruker 70 øre som innslagspunkt på strømstøtte. Dette burde vel bli rettet til 73 øre nå?

"_Fra september 2023 baseres strømstøtten på gjennomsnittlig markedspris (elspotpris) time for time i det lokale prisområdet husholdningen tilhører. Når den overstiger 70 øre per kilowattime (kWh) eksklusive merverdiavgift, vil staten betale 90 prosent av kraftprisen over dette nivået. Lovendringene trådte i kraft 16. juni 2023. Fra og med 1. januar 2024 vil terskelen på 70 øre/kWh endres til 73 øre/kWh._"

[https://www.regjeringen.no/no/tema/energi/regjeringens-stromtiltak](https://www.regjeringen.no/no/tema/energi/regjeringens-stromtiltak/id2900232/?expand=factbox2900261)

**Comment by martinju** [comment]
Tusen takk for at du gjorde meg oppmerksom på dette. 
Dette hadde jeg sett tidligere i vinter, men hadde gått helt i glemmeboken. Har nå oppdatert terkselen og justert prisene tilbake til 01.01.24.
